---
# Source: istio-1.17.2-operator/templates/service_account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: istio-1.17.2-operator
  name: istio-1.17.2-operator
---
# Source: istio-1.17.2-operator/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: istio-1.17.2-operator
rules:
# istio-1.17.2 groups
- apiGroups:
  - authentication.istio-1.17.2.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - config.istio-1.17.2.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - install.istio-1.17.2.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - networking.istio-1.17.2.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - security.istio-1.17.2.io
  resources:
  - '*'
  verbs:
  - '*'
# k8s groups
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions.apiextensions.k8s.io
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - apps
  - extensions
  resources:
  - daemonsets
  - deployments
  - deployments/finalizers
  - replicasets
  verbs:
  - '*'
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
  - update
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - roles
  - rolebindings
  verbs:
  - '*'
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - events
  - namespaces
  - pods
  - pods/proxy
  - pods/portforward
  - persistentvolumeclaims
  - secrets
  - services
  - serviceaccounts
  - resourcequotas
  verbs:
  - '*'
---
# Source: istio-1.17.2-operator/templates/clusterrole_binding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: istio-1.17.2-operator
subjects:
- kind: ServiceAccount
  name: istio-1.17.2-operator
  namespace: istio-1.17.2-operator
roleRef:
  kind: ClusterRole
  name: istio-1.17.2-operator
  apiGroup: rbac.authorization.k8s.io
---
# Source: istio-1.17.2-operator/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: istio-1.17.2-operator
  labels:
    name: istio-1.17.2-operator
  name: istio-1.17.2-operator
spec:
  ports:
  - name: http-metrics
    port: 8383
    targetPort: 8383
    protocol: TCP
  selector:
    name: istio-1.17.2-operator
---
# Source: istio-1.17.2-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: istio-1.17.2-operator
  name: istio-1.17.2-operator
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: istio-1.17.2-operator
  template:
    metadata:
      labels:
        name: istio-1.17.2-operator
      annotations:
        prometheus.io/port: "15014"
        prometheus.io/scrape: "true"
    spec:
      serviceAccountName: istio-1.17.2-operator
      containers:
        - name: istio-1.17.2-operator
          image: gcr.io/istio-1.17.2-testing/operator:1.17-dev
          command:
          - operator
          - server
          - --monitoring-host=127.0.0.1
          - --monitoring-port=15014
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1337
            runAsUser: 1337
            runAsNonRoot: true
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
          env:
            - name: WATCH_NAMESPACE
              value: "istio-1.17.2-system"
            - name: LEADER_ELECTION_NAMESPACE
              value: "istio-1.17.2-operator"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "istio-1.17.2-operator"
            - name: WAIT_FOR_RESOURCES_TIMEOUT
              value: "300s"
            - name: REVISION
              value: ""
