apiVersion: v1
kind: ConfigMap
metadata:
  name: higress-config
  namespace: higress-system
data:
  higress: |-
    tracing:
      sampling: 100
      enable: true
      timeout: 800
      skywalking:
       service: skywalking-oap-server.op-system.svc.cluster.local
       port: 11800
