apiVersion: v1
kind: Service
metadata:
  name: {{ include "cost-exporter.fullname" . }}
  labels:
    {{- include "cost-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8081
      protocol: TCP
      name: http
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "cost-exporter.selectorLabels" . | nindent 4 }}
