apiVersion: v1
kind: Namespace
metadata:
  name: app-system
---
apiVersion: v1
kind: Pod
metadata:
  name: consul-standlone
  namespace: app-system
  labels:
    name: consul-standlone
spec:
  containers:
    - name: consul
      image:  hashicorp/consul:1.12.2
      resources:
        requests:
          cpu: 10m
      ports:
        - containerPort: 8500
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: consul-service
  namespace: app-system
  labels:
    name: consul-standlone
spec:
  clusterIP: None
  ports:
    - name: http-query
      port: 8500
      protocol: TCP
      targetPort: 8500
  selector:
    name: consul-standlone



