apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: http2rpcs.networking.higress.io
spec:
  group: networking.higress.io
  names:
    categories:
      - higress-io
    kind: Http2Rpc
    listKind: Http2RpcList
    plural: http2rpcs
    singular: http2rpc
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              oneOf:
                - not:
                    anyOf:
                      - required:
                          - dubbo
                      - required:
                          - grpc
                - required:
                    - dubbo
                - required:
                    - grpc
              properties:
                dubbo:
                  properties:
                    methods:
                      items:
                        properties:
                          headersAttach:
                            type: string
                          httpMethods:
                            items:
                              type: string
                            type: array
                          httpPath:
                            type: string
                          params:
                            items:
                              properties:
                                paramKey:
                                  type: string
                                paramSource:
                                  type: string
                                paramType:
                                  type: string
                              type: object
                            type: array
                          serviceMethod:
                            type: string
                        type: object
                      type: array
                    service:
                      type: string
                    version:
                      type: string
                  type: object
                grpc:
                  type: object
              type: object
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
          type: object
      served: true
      storage: true
      subresources:
        status: {}
