version: "3"

services:
  front-envoy:
    image: envoyproxy/envoy-alpine:v1.11.2
    volumes:
      - ./front-envoy-zipkin.yaml:/etc/envoy/envoy.yaml
    networks:
      - envoymesh
    expose:
      - "80"
      - "9901"
    ports:
      - "8000:80"
      - "9901:9901"

  service1:
    build:
      context: ./
      dockerfile: Dockerfile-service
    volumes:
      - ./service1-envoy-zipkin.yaml:/etc/envoy/envoy.yaml
    networks:
      envoymesh:
        aliases:
          - service1
    environment:
      - SERVICE_NAME=1
    expose:
      - "80"

  service2:
    build:
      context: ./
      dockerfile: Dockerfile-service
    volumes:
      - ./service2-envoy-zipkin.yaml:/etc/envoy/envoy.yaml
    networks:
      envoymesh:
        aliases:
          - service2
    environment:
      - SERVICE_NAME=2
    expose:
      - "80"

  zipkin:
    image: openzipkin/zipkin
    networks:
      envoymesh:
        aliases:
          - zipkin
    expose:
      - "9411"
    ports:
      - "9411:9411"

networks:
  envoymesh: {}
