apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{.Release.Namespace}}
  name: istio-1.17.2-operator{{- if not (eq .Values.revision "") }}-{{ .Values.revision }}{{- end }}
{{- if .Values.imagePullSecrets }}
imagePullSecrets:
{{- range .Values.imagePullSecrets }}
- name: {{ . }}
{{- end }}
{{- end }}
---
