apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "fadvisor.fullname" . }}
rules:
  - apiGroups: [ '*' ]
    resources: [ '*' ]
    verbs: [ "*" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "fadvisor.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "fadvisor.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "fadvisor.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
