{{ if .Values.craneAgent.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crane-agent
  labels:
    {{- include "crane.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods/eviction
      - pods/status
      - pods
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - nodes/proxy
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/status
      - nodes/finalizers
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - "ensurance.crane.io"
    resources:
      - nodeqoss
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - "ensurance.crane.io"
    resources:
      - podqoss
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - "ensurance.crane.io"
    resources:
      - avoidanceactions
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - "prediction.crane.io"
    resources:
      - timeseriespredictions
      - timeseriespredictions/finalizers
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - update
      - patch
  - apiGroups:
      - "topology.crane.io"
    resources:
      - "*"
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crane-agent
  labels:
    {{- include "crane.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crane-agent
subjects:
  - kind: ServiceAccount
    name: crane-agent
    namespace: {{ .Release.Namespace }}
{{ end }}