{{ if .Values.craneAgent.enable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: crane-agent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crane.labels" . | nindent 4 }}
{{ end }}