apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: craned
  labels:
    {{- include "crane.labels" . | nindent 4 }}
rules:
  - apiGroups: [ '*' ]
    resources: [ '*' ]
    verbs: [ "*" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: craned
  labels:
    {{- include "crane.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: craned
subjects:
  - kind: ServiceAccount
    name: craned
    namespace: {{ .Release.Namespace }}
