{{ if .Values.metricAdapter.enable }}
apiVersion: v1
kind: Service
metadata:
  name: metric-adapter
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crane.labels" . | nindent 4 }}
spec:
  ports:
    - name: https
      port: 443
      targetPort: 6443
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: metric-adapter
{{ end }}