{{ if .Values.metricAdapter.enable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metric-adapter
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crane.labels" . | nindent 4 }}
{{ end }}