apiVersion: v1
kind: Namespace
metadata:
  name: app-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: basic
  namespace: app-system
---
apiVersion: v1
kind: Service
metadata:
  name: basic
  namespace: app-system
  labels:
    app: basic
    service: basic
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: basic
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic
  namespace: app-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic
      version: v1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/scheme: "http"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "80"
      labels:
        app: basic
        version: v1
    spec:
      serviceAccountName: basic
      containers:
        - image: docker.io/2456868764/httpbin:1.0.0
          imagePullPolicy: IfNotPresent
          name: basic
          ports:
            - containerPort: 80
          command:
            - /app/httpbin
          livenessProbe:
            httpGet:
              path: /prob/liveness
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /prob/readiness
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          env:
            - name: SERVICE_NAME
              value: basic
            - name: VERSION
              value: v1
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName

