version: '3'

services:
  front-envoy:
    image: envoyproxy/envoy-alpine:v1.11.2
    volumes:
      - ./front-envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      - envoymesh
    expose:
      # Expose ports 80 (for general traffic) and 9901 (for the admin server)
      - "80"
      - "9901"

  ver151:
    image: ikubernetes/servicemesh-app:latest
    networks:
      envoymesh:
        aliases:
          - version-1.5
          - myapp-v1.5
    environment:
      - SERVICE_NAME=myapp-v1.5-1
    expose:
      - "80"

  ver152:
    image: ikubernetes/servicemesh-app:latest
    networks:
      envoymesh:
        aliases:
          - version-1.5
          - myapp-v1.5
    environment:
      - SERVICE_NAME=myapp-v1.5-2
    expose:
      - "80"

  ver153:
    image: ikubernetes/servicemesh-app:latest
    networks:
      envoymesh:
        aliases:
          - version-1.5
          - myapp-v1.5
    environment:
      - SERVICE_NAME=myapp-v1.5-3
    expose:
      - "80"

  ver161:
    image: ikubernetes/servicemesh-app:latest
    networks:
      envoymesh:
        aliases:
          - version-1.6
          - myapp-v1.6
    environment:
      - SERVICE_NAME=myapp-v1.6-1
    expose:
      - "80"

  ver162:
    image: ikubernetes/servicemesh-app:latest
    networks:
      envoymesh:
        aliases:
          - version-1.6
          - myapp-v1.6
    environment:
      - SERVICE_NAME=myapp-v1.6-2
    expose:
      - "80"

networks:
  envoymesh: {}
