version: '3.3'
services:
  envoy:
    build:
      context: .
      dockerfile: Dockerfile-envoy
    networks:
      envoymesh:
        aliases:
        - envoy
    expose:
    - "80"
    - "9901"

  webserver1:
    image: ikubernetes/mini-http-server:v0.3
    networks:
      envoymesh:
        aliases:
        - webserver1
        - myservice
    expose:
    - "8081"
    depends_on:
    - "envoy"

  webserver2:
    image: ikubernetes/mini-http-server:v0.3
    networks:
      envoymesh:
        aliases:
        - webserver2
        - myservice
    expose:
    - "8081"
    depends_on:
    - "envoy"

networks:
  envoymesh: {}
